# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from automata import checkCharacter, checkTable
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setFixedSize(1000, 600)
        MainWindow.setWindowIcon(QtGui.QIcon("icon.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 241, 91))
        font = QtGui.QFont()
        # font.setFamily("Comfortaa")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 281, 51))
        font = QtGui.QFont()
        # font.setFamily("Montserrat Medium")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 250, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(340, 10, 650, 581))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setColumnWidth(0, 150)
        self.tableWidget.setColumnWidth(1, 140)
        self.tableWidget.setColumnWidth(2, 150)
        self.tableWidget.setColumnWidth(3, 200)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 320, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 460, 151, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 530, 141, 41))
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 380, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.setDisabled(True)
        self.lineEdit.textChanged[str].connect(
            lambda: self.pushButton.setEnabled(self.lineEdit.text() != ""))
        self.pushButton.clicked.connect(self.clickMethod)

        # Button 2
        self.pushButton_2.clicked.connect(self.deleteAll)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automata"))
        self.label.setText(_translate("MainWindow", "Autómata"))
        self.label_2.setText(_translate(
            "MainWindow", "Introduce tu cadena a evaluar:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Estado Actual"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Caracter"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Clase"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Estado Siguiente"))
        self.pushButton.setText(_translate("MainWindow", "Evaluar cadena"))
        self.label_3.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", ""))
        self.pushButton_2.setText(_translate("MainWindow", "Limpiar Todo"))

    def clickMethod(self):
        simbolos = ["letra", "letra", "simbolo", "letra", "digito", "simbolo"]
        sig_estado = 0
        cadena = self.lineEdit.text()
        self.tableWidget.setRowCount(len(cadena))
        for i in range(len(cadena)):
            act_estado = sig_estado
            clase = checkCharacter(cadena[i])
            sig_estado = checkTable(act_estado, clase)

            # Estado actual
            self.tableWidget.setItem(
                i, 0, QtWidgets.QTableWidgetItem(str(act_estado)))
            # Caracter
            self.tableWidget.setItem(
                i, 1, QtWidgets.QTableWidgetItem(cadena[i]))
            # Clase
            self.tableWidget.setItem(
                i, 2, QtWidgets.QTableWidgetItem(simbolos[clase]))
            # Estado siguiente
            self.tableWidget.setItem(
                i, 3, QtWidgets.QTableWidgetItem(str(sig_estado)))

        msg = "Cadena valida" if sig_estado != 5 else "Cadena no valida"

        self.label_3.setText(msg)

        if sig_estado != 5:
            if sig_estado == 1:
                self.label_4.setText("Es un identificador")
            elif sig_estado == 2:
                self.label_4.setText("Es una palabra reservada")
            elif sig_estado == 3:
                self.label_4.setText("Es un identificador")
            elif sig_estado == 4:
                self.label_4.setText("Es un numero")

    def deleteAll(self):
        self.tableWidget.setRowCount(0)
        self.label_3.setText("")
        self.label_4.setText("")
        self.lineEdit.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
